### ISSUE TITLE
Maven coordinates instead of zip location

### ISSUE THREAD

**Issue by theute** [lzoubek/wildfly-extension-maven-plugin#1]
I am very new to the plugin, but wanted to make a suggestion.

Currently the ZIP to extract is defined by .zip path.

It would be nicer if I could give the maven coordinates instead. Without this, we need to create a task to copy locally first.

**Comment by lzoubek** [comment]
Sure, that will address the case, when plugin is used to lay down (maybe) several extensions/subsystems on top of wildfly
