### ISSUE TITLE
install module without standalone.xml extension definition

### ISSUE THREAD

**Issue by marekgregor** [lzoubek/wildfly-extension-maven-plugin#3]
Thank you for marvelous plugin. We use it also for instalation of Wildfly modules with different database drivers (jtds, postgre ...) not present in original installation archive. These modules doesn't need to be specified in standalone.xml as extension (now we fix it, with following run of your plugin to replace &lt;extensions&gt; part definition in standalone.xml to former state - but it is not pretty solution). Therefore it would be nice to omit standalone.xml changes for installation of module by e.g. special configuration property for plugin. 
thanks

**Comment by lzoubek** [comment]
This should be quite easy to implement. Please submit a PR if you want this feature quickly. 

I think the best way is to introduce optional boolean property (ie. registerExtension) with default value = true.

**Comment by LegacyEbenZhang** [comment]
@lzoubek in my pull request #4 I have introduced optional boolean property as suggested
